version: '3.7'

volumes:
    app_volume:
        name: ${PROJECT_NAME}_app_volume
        driver: local
        driver_opts:
            type: nfs
            o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
            device: ":${PWD}"

services:
    go:
        container_name: ${PROJECT_NAME}_go
        image: go_image
        build: ./go
        tty: true
        ports:
            - 8080:8080
            - 59025:59025
        volumes:
            - app_volume:/app

    db:
        container_name: ${PROJECT_NAME}_db
        image: db_image
        build:
            context: ./db
            args:
                MYSQL_USER: ${MYSQL_USER}
                MYSQL_PASSWORD: ${MYSQL_PASSWORD}
                MYSQL_DATABASE: ${MYSQL_DATABASE}
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306
        volumes:
            - ./.data/db:/var/lib/mysql
            - ../migration:/migration
        user: mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
